### ISSUE TITLE
java.lang.RuntimeException: not supported: class org.evosuite.utils.generic.WildcardTypeImpl

### ISSUE THREAD

**Issue by VoglSebastian** [se2p/evosuite#11]
Some classes of the SBST 2020 tool competition have failed:

```
[MASTER] 14:54:37.065 [logback-2] ERROR ClientNodeImpl - Error when generating tests for: com.google.common.collect.FilteredEntryMultimap with seed 27. Configuration id : null
java.lang.RuntimeException: not supported: class org.evosuite.utils.generic.WildcardTypeImpl
        at com.googlecode.gentyref.GenericTypeReflector.erase(GenericTypeReflector.java:44)
        at org.evosuite.utils.generic.GenericClass.satisfiesBoundaries(GenericClass.java:1613)
        at org.evosuite.seeding.CastClassManager.getAssignableClasses(CastClassManager.java:394)
        at org.evosuite.seeding.CastClassManager.selectCastClass(CastClassManager.java:489)
        at org.evosuite.utils.generic.GenericClass.getGenericWildcardInstantiation(GenericClass.java:677)
        at org.evosuite.utils.generic.GenericClass.getGenericParameterizedTypeInstantiation(GenericClass.java:739)
        at org.evosuite.utils.generic.GenericClass.getGenericInstantiation(GenericClass.java:581)
        at org.evosuite.utils.generic.GenericClass.getGenericInstantiation(GenericClass.java:557)
        at org.evosuite.utils.generic.GenericClass.canBeInstantiatedTo(GenericClass.java:300)
        at org.evosuite.setup.TestCluster.cacheGenerators(TestCluster.java:410)
        at org.evosuite.setup.TestCluster.getGeneratorsForSpecialCase(TestCluster.java:825)
        at org.evosuite.setup.TestCluster.getRandomGenerator(TestCluster.java:988)
        at org.evosuite.setup.TestCluster.getRandomGenerator(TestCluster.java:982)
        at org.evosuite.testcase.TestFactory.attemptObjectGeneration(TestFactory.java:845)
        at org.evosuite.testcase.TestFactory.createOrReuseObjectVariable(TestFactory.java:1652)
        at org.evosuite.testcase.TestFactory.createOrReuseVariable(TestFactory.java:1390)
        at org.evosuite.testcase.TestFactory.satisfyParameters(TestFactory.java:2424)
        at org.evosuite.testcase.TestFactory.addMethodFor(TestFactory.java:554)
        at org.evosuite.testcase.TestFactory.insertRandomCall(TestFactory.java:2241)
        at org.evosuite.testcase.mutation.RandomInsertion.insertStatement(RandomInsertion.java:81)
        at org.evosuite.testcase.TestFactory.insertRandomStatement(TestFactory.java:2365)
        at org.evosuite.testcase.factories.RandomLengthTestFactory.getRandomTestCase(RandomLengthTestFactory.java:73)
        at org.evosuite.testcase.factories.RandomLengthTestFactory.getChromosome(RandomLengthTestFactory.java:92)
        at org.evosuite.testcase.factories.RandomLengthTestFactory.getChromosome(RandomLengthTestFactory.java:38)
        at org.evosuite.ga.metaheuristics.GeneticAlgorithm.getRandomPopulation(GeneticAlgorithm.java:408)
        at org.evosuite.ga.metaheuristics.GeneticAlgorithm.generateRandomPopulation(GeneticAlgorithm.java:399)
        at org.evosuite.ga.metaheuristics.GeneticAlgorithm.generateInitialPopulation(GeneticAlgorithm.java:348)
        at org.evosuite.ga.metaheuristics.mosa.AbstractMOSA.initializePopulation(AbstractMOSA.java:352)
        at org.evosuite.ga.metaheuristics.mosa.DynaMOSA.generateSolution(DynaMOSA.java:149)
        at org.evosuite.ga.metaheuristics.TestSuiteAdapter.generateSolution(TestSuiteAdapter.java:114)
        at org.evosuite.strategy.MOSuiteStrategy.generateTests(MOSuiteStrategy.java:123)
        at org.evosuite.TestSuiteGenerator.generateTests(TestSuiteGenerator.java:630)
        at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:205)
        at org.evosuite.rmi.service.ClientNodeImpl.lambda$startNewSearch$0(ClientNodeImpl.java:150)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[MASTER] 14:54:37.181 [main] ERROR SearchStatistics - No statistics has been saved because EvoSuite failed to generate any test case
```

Classes for which this occurred:
* FilteredEntryMultimap (14/60)
* LinkedListMultimap (13/60)
* FilteredMultimapValues (6/60)
* MinMaxPriorityQueue (6/60)
* ImmutableEnumSet (2/60)
* LexicographicalOrdering (2/60)
* ComparatorOrdering (2/60)

Maybe an additional check at:
org.evosuite.utils.generic.GenericClass.satisfiesBoundaries(GenericClass.java:1613)
is maybe enough to fix this issue

**Comment by VoglSebastian** [comment]
I have added an special case for this issue:  f00cac5eafe5a7ea69bcc9a0c1b7f839077bf9a7 .
It prevents the Exception, but i am not sure, if we miss some cases, where the GenericClass is assignable to the Wildcard type.
